# permissions for end users to edit tfruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: orchestrator-api
    app.kubernetes.io/managed-by: kustomize
  name: tfrun-editor-role
rules:
- apiGroups:
  - infra.essity.com
  resources:
  - tfruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.essity.com
  resources:
  - tfruns/status
  verbs:
  - get
