# permissions for end users to view tfruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: orchestrator-api
    app.kubernetes.io/managed-by: kustomize
  name: tfrun-viewer-role
rules:
- apiGroups:
  - infra.infra.essity.com
  resources:
  - tfruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.infra.essity.com
  resources:
  - tfruns/status
  verbs:
  - get
