apiVersion: infra.essity.com/v1alpha1
kind: TfRun
metadata:
  labels:
    app.kubernetes.io/name: orchestrator-api
    app.kubernetes.io/managed-by: kustomize
  name: tfrun-sample-02
spec:
  forProvider:
    credentialsSecretRef: tf-credentials
  source:
    module: https://github.com/vimal-vijayan/my-app.git
    # ref: v0.0.2
    ref: master
  backend:
    cloud:
      hostname: essity.scalr.io
      organization: cet-launchpad
      workspace: demo-workspace-11
  arguments:
    autoApprove: "true"
  vars:
    name: "orchestrator-sample"
