apiVersion: infra.essity.com/v1alpha1
kind: TfRun
metadata:
  labels:
    app.kubernetes.io/name: orchestrator-api
    app.kubernetes.io/managed-by: kustomize
  name: tfrun-sample
spec:
  forProvider:
    credentialsSecretRef: tf-credentials
  source:
    module: https://github.com/vimal-vijayan/my-app.git
    ref: master
    # path: modules/network
  backend:
    cloud:
      hostname: essity.scalr.io
      organization: cet-launchpad
      workspace: demo-workspace-10
      agentPoolId: "ap-v0p08qgiq6mohe7ns"
  arguments:
    autoApprove: "true"
  vars:
    name: "orchestrator-sample"