apiVersion: infra.essity.com/v1alpha1
kind: TfRun
metadata:
  labels:
    app.kubernetes.io/name: orchestrator-api
    app.kubernetes.io/managed-by: kustomize
  name: tfrun-sample
spec:
  forProvider:
    credentialsSecretRef: tf-credentials
  source:
    module: https://github.com/example/terraform-modules.git
    ref: main
    path: modules/network
  backend:
    cloud:
      hostname: essity.scalr.io
      organization: my-org
      workspace: my-workspace
  arguments:
    autoApprove: "true"
  vars:
    region: "eu-west-1"
