apiVersion: v1
kind: Secret
metadata:
  name: tf-credentials
  namespace: orchestrator-api
type: Opaque
data:
  token: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmhZMk5mYVdRaU9pSmhZMk10ZGpCdmRHZ3dkblp3Y0djeGJtaHdZM0FpTENKbGVIQWlPakUzTnpZd09URTRPVElzSW1semN5STZJbk5qWVd4eU9uVnpaWElpTENKcWRHa2lPaUpoZEMxMk1IQTBOR000TlRWdFlUQnlZVzVrY2lKOS4xeTZiNmVEZEdSMHJaVVNpcE9GSzQxU21aUDB1QWZuLVdrRGpUMnN6TzBB
---
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: orchestrator-api
type: Opaque
stringData:
  username: git
  token: ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxx